
[types]

	[types.leaves_type]

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.beachparty]
			palm = true

		[types.leaves_type.abyssal_decor]
			cinnamon = true
			flowering_cinnamon = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			cherry = true
			cheerful_cherry = true
			moody_cherry = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.tconstruct]
			earth_slime = true
			sky_slime = true
			ender_slime = true

		[types.leaves_type.biomesoplenty]
			origin = true
			flowering_oak = true
			maple = true
			orange_autumn = true
			yellow_autumn = true
			rainbow_birch = true
			fir = true
			redwood = true
			white_cherry = true
			pink_cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.dynamictrees]
			oak_undergrowth = true
			jungle = true
			azalea = true
			mangrove = true
			oak = true
			spruce = true
			dark_oak = true
			jungle_undergrowth = true
			birch = true
			flowering_azalea = true
			acacia = true

		[types.leaves_type.dtbop]
			yellow_autumn = true
			willow = true
			white_cherry = true
			umbran = true
			spruce_undergrowth = true
			spruce_twiglet = true
			spruce_poplar = true
			sparse_oak = true
			sparse_acacia = true
			redwood = true
			rainbow_birch = true
			poplar = true
			pink_cherry = true
			palm = true
			orange_autumn = true
			oak_twiglet = true
			mega_dark_oak = true
			maple_twiglet = true
			maple = true
			mahogany = true
			magic_poplar = true
			jungle_twiglet = true
			jacaranda = true
			hellbark_bush = true
			hellbark = true
			flowering_oak_undergrowth = true
			flowering_oak = true
			fir = true
			dying = true
			dark_poplar = true
			dark_oak_twiglet = true
			cypress_willow = true
			acacia_undergrowth = true
			acacia_twiglet = true

		[types.leaves_type.dtupgradeaquatic]
			river = true

		[types.leaves_type.dtautumnity]
			yellow_maple = true
			red_maple = true
			orange_maple = true
			maple = true

		[types.leaves_type.dttconstruct]
			sky_slime = true
			ender_slime = true
			earth_slime = true

		[types.leaves_type.dtquark]
			serene_blossom = true
			sunny_blossom = true
			fiery_blossom = true
			sweet_blossom = true
			frosty_blossom = true
			warm_blossom = true

		[types.leaves_type.fossilsorigins]
			ancient = true

		[types.leaves_type.pizzacraft]
			olive = true
			fruit_olive = true

		[types.leaves_type.enchanted]
			rowan = true
			hawthorn = true
			alder = true

	[types.wood_type]

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.beachparty]
			palm = true

		[types.wood_type.abyssal_decor]
			white_wood = true
			blackwood = true
			cinnamon = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			cherry = true
			wisteria = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.tconstruct]
			greenheart = true
			skyroot = true
			bloodshroom = true
			enderbark = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.biomesoplenty]
			fir = true
			redwood = true
			cherry = true
			mahogany = true
			jacaranda = true
			palm = true
			willow = true
			dead = true
			magic = true
			umbran = true
			hellbark = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.fossilsorigins]
			great_basin_bristlecone_pine = true

		[types.wood_type.pizzacraft]
			olive = true

		[types.wood_type.enchanted]
			rowan = true
			hawthorn = true
			alder = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.buildersaddition]
			hedge = true

		[entries.leaves_type.cfm]
			hedge = true

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.buildersdelight]
			chair_2 = true
			chair_1 = true
			slab_5 = true
			slab_4 = true
			slab_7 = true
			slab_6 = true
			slab_1 = true
			slab_3 = true
			slab_2 = true
			planks_3 = true
			planks_4 = true
			planks_1 = true
			planks_2 = true
			planks_7 = true
			planks_5 = true
			planks_6 = true
			glass_8 = true
			glass_2 = true
			glass_3 = true
			glass_1 = true
			glass_6 = true
			glass_7 = true
			glass_4 = true
			glass_5 = true
			furniture_kit = true
			stairs_4 = true
			stairs_5 = true
			stairs_6 = true
			stairs_7 = true
			stairs_1 = true
			stairs_2 = true
			frame_7 = true
			stairs_3 = true
			frame_8 = true
			frame_5 = true
			frame_6 = true
			frame_3 = true
			frame_4 = true
			frame_1 = true
			frame_2 = true
			table_1 = true
			table_2 = true
			glass_pane_7 = true
			glass_pane_8 = true
			glass_pane_5 = true
			glass_pane_6 = true
			glass_pane_3 = true
			glass_pane_4 = true
			glass_pane_1 = true
			glass_pane_2 = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.buildersaddition]
			support_bracket = true
			cabinet = true
			stool = true
			cupboard = true
			table = true
			bedside_table = true
			shelf = true
			chair = true
			counter_granite = true
			counter_blackstone = true
			bookshelf = true
			arcade = true
			counter_deepslate = true
			bench = true
			small_cupboard = true
			counter_diorite = true
			counter_andesite = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			coffee_table = true
			stripped_kitchen_counter = true
			stripped_bedside_cabinet = true
			desk_cabinet = true
			kitchen_counter = true
			upgraded_gate = true
			crate = true
			stripped_blinds = true
			bedside_cabinet = true
			stripped_cabinet = true
			desk = true
			stripped_kitchen_drawer = true
			kitchen_sink_dark = true
			stripped_desk_cabinet = true
			blinds = true
			stripped_desk = true
			stripped_coffee_table = true
			stripped_crate = true
			table = true
			park_bench = true
			upgraded_fence = true
			stripped_park_bench = true
			cabinet = true
			mail_box = true
			chair = true
			stripped_mail_box = true
			stripped_upgraded_fence = true
			kitchen_drawer = true
			stripped_table = true
			stripped_chair = true
			stripped_kitchen_sink_dark = true
			kitchen_sink_light = true
			stripped_upgraded_gate = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			tiled_door = true
			pegged_planks = true
			secret_door = true
			smooth_planks = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			beach_door = true
			fine_vertical_planks = true
			diamond_bordered_glass = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			detailed_planks = true
			cobweb_trapdoor = true
			barred_trapdoor = true
			airy_trapdoor = true
			pressed_door = true
			planks_panel = true
			solid_trapdoor = true
			boarded_door = true
			meshed_trapdoor = true
			fancy_trapdoor = true
			paper_door = true
			basket_woven_planks = true
			enclosed_planks = true
			double_herringbone_planks = true
			crated_planks = true
			classic_windowed_trapdoor = true
			wickered_planks = true
			heavy_trapdoor = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			polished_planks = true
			ornate_bared_glass_pane = true
			wall_torch = true
			glass_door = true
			paneled_door = true
			leafy_trapdoor = true
			pointless_trapdoor = true
			planks_shavings = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			classic_trapdoor = true
			circle_glass = true
			torch = true
			screen_door = true
			crossed_planks = true
			cross_laced_planks = true
			railed_planks = true
			planks_mosaic = true
			circle_glass_pane = true
			versailles_planks = true
			woven_glass = true
			woven_trapdoor = true
			gated_door = true
			supported_door = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			line_bared_glass = true
			slanted_planks = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			tiled_planks = true
			dual_paneled_door = true
			square_glass_pane = true
			thin_planks = true
			warted_trapdoor = true
			horizontal_lined_glass = true
			natural_planks = true
			brick_bond_planks = true
			bordered_glass_pane = true
			sliding_door = true
			bordered_glass = true
			shack_door = true
			diagonal_planks = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			fortified_door = true
			snowflake_glass = true
			heavy_door = true
			stacked_planks = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true

		[entries.wood_type.quark]
			vertical_planks = true
			hollow_log = true
			bookshelf = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			stripped_post = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			waffle_door = true
			cottage_door = true
			swamp_door = true
			barn_door = true
			classic_door = true
			beach_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			glass_door = true
			mystic_door = true
			bark_glass_door = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			log_bridge_stair = true
			rope_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.furnish]
			kitchen_cabinet = true
			log_bench = true
			shelf = true
			square_table = true
			stool = true
			pedestal_table = true
			crate = true
			coffin = true
			cabinet = true
			bench = true
			shutter = true
			bedside_table = true
			wardrobe = true
			ladder = true
			table = true
			chair = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwwindows]
			plank_four_window = true
			window2 = true
			stripped_log_window = true
			plank_window2 = true
			louvered_shutter = true
			plank_pane_window = true
			stripped_log_window2 = true
			log_parapet = true
			stripped_log_four_window = true
			plank_window = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			blinds = true
			plank_parapet = true
			window = true
			shutter = true

		[entries.wood_type.mcwfences]
			picket_fence = true
			wired_fence = true
			pyramid_gate = true
			highley_gate = true
			stockade_fence = true
			horse_fence = true

		[entries.wood_type.mcwlights]
			soul_tiki_torch = true
			tiki_torch = true

		[entries.wood_type.hnh]
			parquet = true
			sanded_wood = true
			trim = true

		[entries.wood_type.friendsandfoes]
			beehive = true

